### ISSUE TITLE
HI, can the library be used in a production environment?

### ISSUE THREAD

**Issue by HebeBlock** [escada-finance/sia-js#3]
Hi, we found your sia-js library today, is it available for normal use?

**Comment by HebeBlock** [comment]
I tried to broadcast a piece and found that 502 appeared
![image](https://user-images.githubusercontent.com/39998387/101235069-1cf0c180-3700-11eb-81ea-c4dc5ea737a2.png)

**Comment by DaWe35** [comment]
Hi @HebeBlock is it working for you? I'm only using the seed generation method in production right now.

**Comment by HebeBlock** [comment]
> Hi @HebeBlock is it working for you? I'm only using the seed generation method in production right now.

Yes，I passed all the cases, but it will take some time to test
